[package]
name = "path-planner"
version = "0.1.0"
edition = "2021"
authors = [
    "Andrew Sheng <asheng618@gmail.com>"
]

[dependencies]
piston = "0.53.0"
piston2d-graphics = "0.43.0"
pistoncore-glutin_window = "0.71.0"
piston2d-opengl_graphics = "0.82.0"
quadtree_rs = "0.1.2"
rand = "0.8.5"